services:
  postgres:
    image: postgres:17.2
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES__NAME}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      log_destination: stderr
      logging_collector: on
      log_directory: /var/lib/postgresql/data/log
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES__NAME} -U ${POSTGRES__USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES__PORT}:${POSTGRES__PORT}"
